### ISSUE TITLE
Logo on the website

### ISSUE THREAD

**Issue by weeman1337** [flossevents/website#11]
This issue is about getting the logo on the website.

**Comment by weeman1337** [comment]
@dreirik what about that?

![flossevents-logo](https://user-images.githubusercontent.com/6216686/68238777-175f0e80-000a-11ea-8872-582546b366ce.png)

**Comment by dreirik** [comment]
I think this is too big : )

what about putting it on the right side, after 2020?

And can we give it a try with the green version? I now tried it also on our social media accounts. please have a look and give me feedback what version you prefer.

**Comment by weeman1337** [comment]
> what about putting it on the right side, after 2020?

That's now an unexpected position for me (and maybe other user). Why? Logos on websites are on the top left. If you click it, you will be sent to the start page.

Anyway:

*red, right*

![fe_red_right](https://user-images.githubusercontent.com/6216686/68488768-0ef31780-0246-11ea-8b0b-14764167b8a6.png)
 
*green, right*

![fe_green_right](https://user-images.githubusercontent.com/6216686/68488904-59749400-0246-11ea-9d8f-f1b1e93492fb.png)

**Comment by weeman1337** [comment]
New log is online → closing issue
