### ISSUE TITLE
some country names miss writing out

### ISSUE THREAD

**Issue by dreirik** [flossevents/website#20]
some of the country names use their 2-digit-code instead of the outwritten country name. This is currently true for UK, IE, UK, AU, UA. 

example: "Collaborations Workshop in Belfast, UK"

**Comment by weeman1337** [comment]
I've taken that from the previous webite. I'll add the long names for these countries.

**Comment by weeman1337** [comment]
> UA

Just a question: why is an event from Australia listed?

**Comment by weeman1337** [comment]
Found it: @dreirik the correct country code for Austria is **AT**. I've corrected that in the CSV.

**Comment by weeman1337** [comment]
Country names have been added → closing
