### ISSUE TITLE
change to /2020 list as default

### ISSUE THREAD

**Issue by dreirik** [flossevents/website#27]
currently the index on /foss.events defaults to the 2019 list. This should be changed to the /2020 list as this is a more appealing list meanwhile.

**Comment by weeman1337** [comment]
@dreirik should we switch the index page to 2020 then? That means https://floss.events/ → 2020 and https://floss.events/2019 → 2019

**Comment by weeman1337** [comment]
As discussed we will do it like this

**Comment by weeman1337** [comment]
• 2020 is now the default page
• As discussed there is a "basic menu" 2019 | 2020
• Clicking the headline leads to 2020
• I've added "Upcoming events *in YEAR*" because otherwise I'm lost as a user
