### ISSUE TITLE
Integrate new logo

### ISSUE THREAD

**Issue by weeman1337** [flossevents/website#9]
As we now have a new shiny logo we want to publish that on the page.

**Acceptance tests**

* [x] Logo source files available in Git @dreirik 
* [x] Logo files available as PNG in Git @weeman1337 
* [ ] ~~Logo files available as SVG in Git @weeman1337~~ skipped
* [ ] ~~Logo integrated on the new website https://test.floss.events/ @weeman1337~~ skipped

**Comment by weeman1337** [comment]
@dreirik could you please provide the logo source files? After that I could create some files to work with on the website.

I could imagine putting the new logo on top in a horizontal style. Like that:

![Screenshot_2019-11-03 FLOSS Events in Europe](https://user-images.githubusercontent.com/6216686/68083465-ff7c6480-fe28-11e9-937c-38327f73ca4b.png)

What do you think?

**Comment by dreirik** [comment]
@weeman1337 see here: https://github.com/flossevents/website/tree/master/logo

however, I am not sure about the use of the logo like in your screenshot, looks unexpected.

currently the more important use is to have it for sfscon.it, the integration into the webpage is 2nd.

btw, what about this one? https://github.com/flossevents/website/blob/master/logo/logo-mit-urlsign-and-br-star.png

**Comment by weeman1337** [comment]
> the integration into the webpage is 2nd.

So, for now there is no logo on the website: https://test.floss.events/ Lets integrate it when creating the menu.
